# Documentation can be found here: https://goreleaser.com

before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/waterfall/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X github.com/null93/waterfall/internal.Version={{ .Version }}"
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/null93/waterfall
    description: Cloudformation CLI tool to analyze and visualize stack events as a waterfall diagram
    maintainer: Rafael Grigorian <rafael@grigorian.org>
    vendor: null93
    bindir: /usr/bin
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux

brews:
  - repository:
      owner: null93
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://github.com/null93/waterfall
    description: Cloudformation CLI tool to analyze and visualize stack events as a waterfall diagram
    test: |
      system "#{bin}/waterfall -v"

